### ISSUE TITLE
Further review of NSS backed SunPKCS#11 registration.

### ISSUE THREAD

**Issue by darranl** [wildfly-security/elytron-subsystem#29]
It appears that initialisation by a one time only event so reloads and redefining services is going to be problematic.

**Comment by darranl** [comment]
12:14:24,298 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-12) MSC000001: Failed to start service elytron.provider-loader.pkcs#11: org.jboss.msc.service.StartException in service elytron.provider-loader.pkcs#11: WFLYELY00004: Unable to start the service.
	at org.wildfly.extension.elytron.ProviderLoaderService.start(ProviderLoaderService.java:105)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.wildfly.extension.elytron.ProviderLoaderService.loadProviders(ProviderLoaderService.java:134)
	at org.wildfly.extension.elytron.ProviderLoaderService.start(ProviderLoaderService.java:86)
	... 5 more
Caused by: java.security.ProviderException: Secmod module already configured
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:276)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:107)
	... 11 more

**Comment by darranl** [comment]
This also seems to be present in OpenJDK - will get a bug reported there and see if we can get that addressed first.

Also need to verify if we can have two instances registered but against different NSS databases.

This is probably not an issue for non-NSS based PKCS#11.

**Comment by darranl** [comment]
Discussed this during today's status call - opinion is that we may want to write a custom workaround just for this class.
